export default {
  base: {
    name: '布局组件',
    componentList: [{
      name: '按钮',
      subname: 'FmButton',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/button.png',
      path: 'component/button'
    }, {
      name: '通用列表项',
      subname: 'FmItem',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/item.png',
      path: 'component/item'
    }, {
      name: '开关按钮',
      subname: 'FmSwitch',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/switch.png',
      path: 'component/switch'
    }, {
      name: '轮播',
      subname: 'FmSlider',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/slider.png',
      path: 'component/slider'
    }, {
      name: '底栏',
      subname: 'FmFooter',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/footer.png',
      path: 'component/footer'
    }, {
      name: '蒙层',
      subname: 'FmOverlay',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/overlay.png',
      path: 'component/overlay'
    }, {
      name: '侧边弹出窗口',
      subname: 'FmPopup',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/popup.png',
      path: 'component/popup'
    }]
  },
  container: {
    name: '导航组件',
    componentList: [{
      name: '导航栏',
      subname: 'FmTitlebar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/titlebar.png',
      path: 'component/titlebar'
    }, {
      name: '搜索栏',
      subname: 'FmSearchbar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/searchbar.png',
      path: 'component/searchbar'
    }, {
      name: '标签页',
      subname: 'FmTabPage',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/tabpage.png',
      path: 'component/tabPage'
    }, {
      name: '底部操作栏',
      subname: 'FmTabbar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/tabbar.png',
      path: 'component/tabbar'
    }]
  },
  other: {
    name: '数据输入',
    subname: 'Other conponent',
    componentList: [{
      name: '输入框',
      subname: 'FmInput',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/input.png',
      path: 'component/input'
    }, {
      name: '多选项',
      subname: 'FmCheckListGroup & FmCheckbox',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/check.png',
      path: 'component/checklist'
    }, {
      name: 'List 多选列表',
      subname: 'fm-multi-check-group & fm-multi-check-cell',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/checklist.png',
      path: 'component/multiCheck'
    }, {
      name: '星级评分',
      subname: 'FmRater',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/rater.png',
      path: 'component/rater'
    }, {
      name: '滑块',
      subname: 'FmSliderBar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/sliderbar.png',
      path: 'component/sliderbar'
    }]
  },
  interaction: {
    name: '数据展示',
    componentList: [{
      name: '文本',
      subname: 'FmText',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/text.png',
      path: 'component/text'
    }, {
      name: '富文本',
      subname: 'RichText',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/richtext.png',
      path: 'component/richText'
    }, {
      name: '图标',
      subname: 'FmIcon',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/icon.png',
      path: 'component/icon'
    }, {
      name: '标签',
      subname: 'FmTag',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/tag.png',
      path: 'component/tag'
    }, {
      name: '标签墙',
      subname: 'FmTagWall',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/tagwall.png',
      path: 'component/tagWall'
    }, {
      name: '简单列表',
      subname: 'FmSimpleList',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/simplelist.png',
      path: 'component/simpleList'
    }, {
      name: '折叠文本',
      subname: 'FmFoldableText',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/foldabletext.png',
      path: 'component/foldableText'
    }]
  },
  form: {
    name: '用户操作',
    componentList: [{
      name: '底部文字按钮',
      subname: 'FmTextbar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/textbar.png',
      path: 'component/textbar'
    }, {
      name: '底部腰圆按钮',
      subname: 'FmBtnbar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/btnbar.png',
      path: 'component/btnbar'
    }, {
      name: '引导提示',
      subname: 'FmTips',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/tips.png',
      path: 'component/tips'
    }, {
      name: '底部提示',
      subname: 'FmSnackBar',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/snackbar.png',
      path: 'component/snackbar'
    }, {
      name: '弹框',
      subname: 'FmDialog',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/dialog.png',
      path: 'component/dialog'
    }, {
      name: '气泡菜单',
      subname: 'FmPopOver',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/popover.png',
      path: 'component/popover'
    }, {
      name: '底部删除弹框',
      subname: 'FmActionSheet',
      icon: 'http://p1nq9peby.bkt.clouddn.com/weex-flymeui/actionsheet.png',
      path: 'component/actionSheet'
    }]
  }
};
